language: go

sudo: false

services:
    - mongodb

go:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - tip

env:
    global:
        secure: "Iw5+Z48T/MC+AcayL2HEgLhXxkF52HAnt4lDba1Ek1XDGNFPvtIAUMZ2BED4/G0QcXbxKRqKxgEjKwrVvX0HTdE41y+pLKImPJeTd2rkbfPWI5xYgNuLAWkrhuxUxEx4UIr87Mw/L20Nk7plppVzN/CQ6x9oLXXdWDm/Www7GvMlOmlsqoaCqh1pjA/ZfJl12cAaOi3Se1UiupAbwn2iH2J7fiU0Ur7yAClmkK7K092GYVeJOPcIZem3L5f36m6RrkIERxVAKQ2fVz+fiO3+wROjduSXt1ABJSvneujTK/178e9OuAuD5WBuiWUi7gDWn6i0G712Dywp8reZ7b9PFVAxwcFkkQg35jGxkV5FFYLohaOG2hAZmb44YGYDkH98qHFX+ox99OxAbHEUsmzShU0TXG2LJ5MizwLVtoH071Os5NGCNov5Xq2HQbsGN95fkU7yi0p7uVIGefk3mBUkrcp7KuhOq+xaWOkD7RhacrwxSEoEaJQp9hl83XcSCqfET3pkix8FZicTVPDIgtYk/nhjKMlvIWd1Q9HPvidEwlp3TAW3lmyu+hf9ivt7wPM2PA7zx8TO/g4ryo21pCo11JiCPUFCf2Fif2m6aXeu3KPndeC7krggQYPQ9GGsPAGk3rfHomjAnSWYnmhg3lAef8sGlOPydzY+2LDCCHI6rBo="

    MONGO_URI: 127.0.0.1:27017/scds_test

before_install:
    - wget https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.tar.gz
    - tar zxf glide-0.10.2-linux-amd64.tar.gz
    - mv ./linux-amd64/glide /usr/bin/
    - chmod +x /usr/bin/glide

install:
    - make test-install

# Wait for mongodb to start
before_script:
    - sleep 2

script:
    - make test-travis
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken=$COVERALLS_TOKEN
